Added custom ID generation
Kavyans18/Mongodb_Book pull request #1
Opened 2023-03-30 13:45 UTC by Kavyans18

2023-03-30 13:46 UTC, Kavyans18 commented
Added custom ID Generation

2023-03-30 17:37 UTC, Velarian requested changes

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/util/MyIdGenerator.java
> +        int randomNum = (int) (Math.random() * 9000) + 1000; // generate a random 4-digit number
this might generate the same id for different books, it's unlikely but it is possible so a developer needs to be aware of that aspect. use some different method of generation

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
bu.setBookId(book.getBookId());  this should be removed

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
>      }
add some minimum checks

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
>      }
stop using sysouts also dont return null
return proper error message

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/controller/BookController.java
use loggers since you finished it, it will be handy

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/controller/BookController.java
>      }
avoid unnecessary variables creation

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookService.java
>  }
service declaration and implementation should be in different packages

2023-03-30 17:37 UTC, Velarian commented on DBMongo/src/main/java/com/pws/DBMongo/entity/Book.java
> +    private String bookId;
naming conventions need to be maintained

2023-03-31 06:26 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
Changed variable int id to int bookId

2023-03-31 06:27 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
>      }
done

2023-03-31 06:27 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
removed and updated

2023-03-31 06:27 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
>      }
Updated

2023-03-31 06:27 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookServiceImp.java
>      }
Created exception

2023-03-31 07:37 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/controller/BookController.java
Done

2023-03-31 07:39 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/controller/BookController.java
>      }
I have created a variable to store a list of books that I can return inside the ResponseEntity object. I am not sure what changes I can make to that. Guide me on that.

2023-03-31 07:43 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/service/BookService.java
>  }
As per my knowledge on the folder structure I have created a service package inside which a bookService Interface which is implemented in the bookServiceImp class. I am not sure if I will have to create a different package for that. Can I get more clarity on that aspect?

2023-03-31 07:45 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/entity/Book.java
> +    private String bookId;
Willing to learn and make changes if I can get some guidance on that

2023-03-31 07:52 UTC, Kavyans18 commented on DBMongo/src/main/java/com/pws/DBMongo/util/MyIdGenerator.java
> +        int randomNum = (int) (Math.random() * 9000) + 1000; // generate a random 4-digit number
I have tried a different method that uses UUID. Kindly check and let me know if it is fine, else I am open to work more on that.

2023-03-31 08:01 UTC, closed without merging